### ISSUE TITLE
invalid syntax with Python 3.4.4

### ISSUE THREAD

**Issue by ker0r0** [MinoMino/mindl#2]
I am using with Python 3.4.4, mindl 0.3, pillow 3.4.2, and PhantomJS 1.9.8.
I've got these console errors and I didn't have any ghostdriver.log.

**For eBookJ**
```
python -m mindl -o username=myemail@mail.com -o password=mypassword "https://br.xxxxxxx.jp/br/reader/viewer/view.html?sessionid=******&keydata=******&shopID=exxxxxxxJapan"
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\mindl\__main__.py", line 22, in <module>
    main()
  File "C:\Python34\lib\site-packages\mindl\cli.py", line 117, in main
    pm = PluginManager()
  File "C:\Python34\lib\site-packages\mindl\plugin_manager.py", line 40, in __in
it__
    module = importlib.import_module(modname)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Python34\lib\site-packages\mindl\plugins\animatebookstore.py", line 2
6, in <module>
    import mindl.plugins.binb as binbapi
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\__init__.py", line 1, i
n <module>
    from .binb_api import BinBApi, BinBApiError, SERVERTYPE_SBC, SERVERTYPE_STAT
IC, USER_AGENT
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\binb_api.py", line 294
    params = dict(cid=self.cid, k=self.k, **self._kwargs, **kwargs)
                                                        ^
SyntaxError: invalid syntax
```

**For BL!**
```
python -m mindl "https://xxxxxxxxxx.jp
/bviewer/?cid=*******&rurl=*******"
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\mindl\__main__.py", line 22, in <module>
    main()
  File "C:\Python34\lib\site-packages\mindl\cli.py", line 117, in main
    pm = PluginManager()
  File "C:\Python34\lib\site-packages\mindl\plugin_manager.py", line 40, in __in
it__
    module = importlib.import_module(modname)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Python34\lib\site-packages\mindl\plugins\animatebookstore.py", line 2
6, in <module>
    import mindl.plugins.binb as binbapi
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\__init__.py", line 1, i
n <module>
    from .binb_api import BinBApi, BinBApiError, SERVERTYPE_SBC, SERVERTYPE_STAT
IC, USER_AGENT
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\binb_api.py", line 294
    params = dict(cid=self.cid, k=self.k, **self._kwargs, **kwargs)
                                                        ^
SyntaxError: invalid syntax
```

**For BL!**
```
python -m mindl "https://bookxxxx.jp
/product/index/title_id/*******/vol_no/001"
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\mindl\__main__.py", line 22, in <module>
    main()
  File "C:\Python34\lib\site-packages\mindl\cli.py", line 117, in main
    pm = PluginManager()
  File "C:\Python34\lib\site-packages\mindl\plugin_manager.py", line 40, in __in
it__
    module = importlib.import_module(modname)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Python34\lib\site-packages\mindl\plugins\animatebookstore.py", line 2
6, in <module>
    import mindl.plugins.binb as binbapi
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\__init__.py", line 1, i
n <module>
    from .binb_api import BinBApi, BinBApiError, SERVERTYPE_SBC, SERVERTYPE_STAT
IC, USER_AGENT
  File "C:\Python34\lib\site-packages\mindl\plugins\binb\binb_api.py", line 294
    params = dict(cid=self.cid, k=self.k, **self._kwargs, **kwargs)
                                                        ^
SyntaxError: invalid syntax
```

**Comment by MinoMino** [comment]
Ah, right. I've been using Python 3.5 for a while now and forgot an arbitrary number of unpackings was [a new addition](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations).

I mean, I could fix that, but considering I'm not really checking if anything works in 3.4 when I'm developing, I'll probably end up using something >=3.5 at some point again. I think I'll just explicitly state mindl's for 3.5+ and just leave it as it is.

Thanks for the heads-up and I hope it's not too much of an inconvenience having to use 3.5.

EDIT: By the way, that's part of the BinB Reader plugins (BookLive and AnimateBookstore), so if you happen to not need those, then you could also get around it by just renaming `booklive.py` and `animatebookstore.py` in `C:\Python34\lib\site-packages\mindl\plugins\` to something else and it'll probably start working again.

**Comment by ker0r0** [comment]
Okay, I've got what you are thinking about it. Thanks anyway.
